name: Deploy Medusa to EC2

on:
  push:
    branches:
      - main  # Trigger the workflow when code is pushed to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code from the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up SSH access to EC2 using the private key stored in Secrets
    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.4
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    # Step 3: Install Docker and Docker Compose on EC2 (if not installed)
    - name: Install Docker on EC2
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
        sudo apt-get update
        sudo apt-get install -y docker.io docker-compose
        sudo systemctl start docker
        sudo usermod -aG docker ubuntu
        EOF

    # Step 4: Copy the project files to the EC2 instance
    - name: Copy files to EC2
      run: |
        scp -o StrictHostKeyChecking=no -r ./* ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/home/ubuntu/medusa

    # Step 5: Run Docker Compose to build and deploy the Medusa app on EC2
    - name: Deploy Medusa using Docker Compose
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
        cd /home/ubuntu/medusa
        sudo docker-compose down
        sudo docker-compose up -d --build
        EOF

