version: '3.8'

services:
  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: medusa_user  # Updated to new user
      POSTGRES_PASSWORD: chinni    # Updated to new password
      POSTGRES_DB: medusa_db
    volumes:
      - medusa-data:/var/lib/postgresql/data
    networks:
      - medusa-network

  medusa:
    build:
      context: ./task-5  # Path to the Dockerfile directory
    image: chinni111/medusa:latest
    ports:
      - "9000:9000"
    environment:
      DATABASE_URL: postgres://medusa_user:chinni@db:5432/medusa_db  # Updated to new credentials
    depends_on:
      - db
    networks:
      - medusa-network
    command: ["sh", "-c", "npm run seed && npx medusa user -e sam@sam.com -p sam && medusa migrations run && npm run start"]

volumes:
  medusa-data:

networks:
  medusa-network:
