name: Deploy to EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.2  # Check for the latest version
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            set -x
            echo "Starting deployment"
            cd /home/ubuntu/medusa || { echo "Failed to change directory"; exit 1; }
            sudo docker-compose pull || { echo "Failed to pull Docker images"; exit 1; }
            sudo docker-compose down || { echo "Failed to stop Docker containers"; exit 1; }
            sudo docker-compose up -d || { echo "Failed to start Docker containers"; exit 1; }
            echo "Deployment finished"
          debug: true
          timeout: 10m
