name: Deploy Medusa to EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.4
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

    - name: Copy files to EC2
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@3.239.45.153 "mkdir -p /home/ubuntu/medusa-backend"
        scp -o StrictHostKeyChecking=no -r task-5/* ubuntu@3.239.45.153:/home/ubuntu/medusa-backend/
        scp -o StrictHostKeyChecking=no task-5/docker-compose.yml ubuntu@3.239.45.153:/home/ubuntu/medusa-backend/
        scp -o StrictHostKeyChecking=no task-5/Dockerfile ubuntu@3.239.45.153:/home/ubuntu/medusa-backend/

    - name: SSH into EC2 and deploy
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@3.239.45.153 << 'EOF'
          set -e
          cd /home/ubuntu/medusa-backend || exit 1
          sudo docker-compose down || true
          sudo docker-compose up -d --build
        EOF
